<?php

namespace App\PDFReports;

use Dompdf\Dompdf;
use Dompdf\Options;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class WelcomeLetterListListingReport
{
    public function generate(Request $request)
    {
        // Base query
        $query = DB::table('listings');
        // Run query
        $letters = $query->where('Welcome', 0)->get();
        $html = '<style>
        body {
                font-family: Arial, sans-serif;
                font-size: 8pt;
            }
            .header-container {
                width: 100%;
                margin-bottom: 10px;
                text-align: left;
            }
            .header {
                font-weight: bold;
                font-size: 12pt;
            }
            .no-results {
            text-align: center; 
            margin-top: 50px; 
            font-size: 10pt;
            font-weight: bold;
        }
             table {
                border-collapse: collapse;
                width: 100%;
                font-size: 8pt;
                transform: scale(0.9);
                transform-origin: top left;
            }
            th, td {
                border: 1px solid #000;
                padding: 4px 6px;
                text-align: left;
            }
            th {
                background-color: #f2f2f2;
                font-weight: bold;
            }
            
            .single-layout {
                width: 100%;
                border: 1px solid #000;
                margin-top: 20px;
                border-collapse: collapse;
            }
            .single-layout td {
                border: 1px solid #000;
                padding: 6px;
                font-size: 8pt;
            }
            .single-label {
                font-weight: bold;
                background: #f2f2f2;
                width: 20%;
            }
            </style>';


        // Header
        $html .= '
        <div class="header-container">
            <div class="header">Executive Business Brokers</div>
            <div class="header">Welcome Letters</div>
            <div style="text-align:right;">As of: ' . now()->format('n/j/Y') . '</div>
        </div>';

        // If results
        if ($letters->count() > 0) {
            // List layout
            $html .= '<table>
                    <thead>
                        <tr>
                            <th>ListingID</th>
                            <th>DBA</th>
                            <th>SellerFName</th>
                            <th>SellerLName</th>
                            <th>SHomeAdd1</th>
                            <th>SHomeAdd2</th>
                            <th>SCity</th>
                            <th>SState</th>
                            <th>SZip</th>
                            <th>Address1</th>
                            <th>Address2</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Zip</th>
                            <th>AgentFName</th>
                            <th>AgentLName</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody>';

            foreach ($letters as $letter) {
                $agentInfo = DB::table('agents')->where('AgentID', $letter->AgentID)->first();
                $html .= '<tr>
                        <td>' . e($letter->ListingID) . '</td>
                        <td>' . e($letter->DBA ?? '') . '</td>
                        <td>' . e($letter->SellerFName) . '</td>
                        <td>' . e($letter->SellerLName) . '</td>
                        <td>' . e($letter->SHomeAdd1) . '</td>
                        <td>' . e($letter->SHomeAdd2) . '</td>
                        <td>' . e($letter->SCity) . '</td>
                        <td>' . e($letter->SState) . '</td>
                        <td>' . e($letter->SZip) . '</td>
                        <td>' . e($letter->Address1) . '</td>
                        <td>' . e($letter->Address2) . '</td>
                        <td>' . e($letter->City) . '</td>
                        <td>' . e($letter->State) . '</td>
                        <td>' . e($letter->Zip) . '</td>
                        <td>' . e($agentInfo->FName ?? '') . '</td>
                        <td>' . e($agentInfo->LName ?? '') . '</td>
                        <td>' . e($letter->Email) . '</td>
                    </tr>';
            }

            $html .= '</tbody></table>';
            $html .= "<div class='footnotes' style='font-size:8px; line-height:1.4; font-family: Arial, sans-serif; width:60%'>
                    <p><strong>Footnotes and Legend:</strong><br>
                        Adjusted Profit - A calculation showing the cash flow generated by the Business for the most recent fiscal or
                        calendar year, unless otherwise indicated, by adding back to the net profit those costs that are discretionary
                        to the Seller, INCLUDING the owner's salary and benefits, or in an absentee-run business, the Manager's salary
                        and benefits, non-cash benefits such as depreciation (in most situations) and amortization, and certain
                        non-recurring or unusual expenses such as Seller Perks. Broker has not audited the books and records and
                        accordingly does not warrant the accuracy or correctness of information. Purchaser must conduct his / her own
                        investigation to determine accuracy of financial information.
                    </p>
                    <p style='margin-top:10px; text-align:center;'>
                        2583 Morris Ave Union, NJ 07083
                        Phone: (908)851-9040 | Fax: (908)851-9066
                        Email: <a href='mailto:sales@execbb.com'>sales@execbb.com</a>
                        Website: <a href='https://www.execbb.com'>https://www.execbb.com</a>
                    </p>
                    <p style='margin-top:5px; text-align:center;'>
                        <strong>Website: <a href='https://www.execbb.com'>https://www.execbb.com</a></strong>
                    </p>

                    <p style='margin-top:5px; font-style:italic; text-align:center;'>
                        *All information is from sources deemed reliable and is submitted subject to errors, omissions, change of price,
                        rental, prior sale and withdrawal notice.
                    </p>
                </div>";
        } else {
            $html .= '<div class="no-results">No results found for the given filters.</div>';
        }

        // Generate PDF
        /* $options = new Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isRemoteEnabled', true);

        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('legal', 'landscape');
        $dompdf->render();

        return $dompdf->output(); */
        return $html;
    }
}
